package in

import (
	"context"
	"time"

	domain "github.com/role-organizado/backend-go-role-organizado/internal/domain/payment"
)

// ---- SavedCard input types ----

// CreateSavedCardInput holds data to create a new saved credit card.
type CreateSavedCardInput struct {
	UserID      string
	LastFour    string
	Brand       string
	HolderName  string
	ExpiryMonth int
	ExpiryYear  int
	IsDefault   bool
}

// QueryInstallmentsInput holds filter params for querying installments.
type QueryInstallmentsInput struct {
	EventID string // optional
	UserID  string // optional
	Status  string // optional
}

// GetUserInstallmentsInput holds params for getting a user's own installments.
type GetUserInstallmentsInput struct {
	UserID string
	Status string // optional
}


// QueryInstallmentsUseCase handles installment query endpoints.
type QueryInstallmentsUseCase interface {
	Query(ctx context.Context, in QueryInstallmentsInput) ([]domain.Installment, error)
	GetForUser(ctx context.Context, in GetUserInstallmentsInput) ([]domain.Installment, error)
}

// CreatePagamentoInput contains fields to create a new recurring payment.
type CreatePagamentoInput struct {
	EventoID        string
	UsuarioID       string
	Descricao       string
	Valor           float64
	MetodoPagamento domain.MetodoPagamento
	DataVencimento  time.Time
	Observacao      string
}

// UpdatePagamentoInput holds optional fields to update a payment.
type UpdatePagamentoInput struct {
	Descricao       *string
	Valor           *float64
	DataVencimento  *time.Time
	Observacao      *string
}

// ConfirmarPagamentoInput holds data to confirm a payment as settled.
type ConfirmarPagamentoInput struct {
	DataPagamento time.Time
	Comprovante   string // optional GridFS file ID
}

// UpsertConfigPagamentoInput holds payment config for an event.
// Fee policy fields mirror Java AtualizarConfigPagamentoUseCase: the caller
// supplies the snapshot values; the use case generates FeePolicyVersion.
type UpsertConfigPagamentoInput struct {
	EventoID         string
	UsuarioID        string
	MetodosPagamento []domain.MetodoPagamento
	PrazoPagamento   *time.Time
	ChavePix         string
	InstrucoesBoleto string

	// Fee policy snapshot fields (gap report §6.3).
	PlatformFeePercent    float64 // platformFeePercent
	PspFeePercent         float64 // pspFeePercent
	PaymentProvider       string  // "ASAAS" | "MOCK"
	PaymentFrequency      string
	PaymentReleaseTrigger string
}

// ReaplicarFeePolicyNasConfigsInput carries the fee values to reapply across
// all existing EventoConfigPagamento records (admin-only operation).
type ReaplicarFeePolicyNasConfigsInput struct {
	PlatformFeePercent float64
	PspFeePercent      float64
	// VersionID is an opaque identifier used to build the snapshot version string.
	// If empty, a UUID is generated by the use case.
	VersionID   string
	RequesterID string
}

// ReaplicarFeePolicyResult summarises the outcome of a bulk fee reapplication.
type ReaplicarFeePolicyResult struct {
	UpdatedCount int64
}

// CreatePagamentoUseCase creates a new payment record.
type CreatePagamentoUseCase interface {
	Execute(ctx context.Context, in CreatePagamentoInput) (*domain.PagamentoMensal, error)
}

// GetPagamentoUseCase retrieves a payment by ID.
type GetPagamentoUseCase interface {
	Execute(ctx context.Context, id, requesterID string) (*domain.PagamentoMensal, error)
}

// ListPagamentosUseCase lists all payments for an event.
type ListPagamentosUseCase interface {
	Execute(ctx context.Context, eventoID, requesterID string) ([]domain.PagamentoMensal, error)
}

// UpdatePagamentoUseCase partially updates a payment.
type UpdatePagamentoUseCase interface {
	Execute(ctx context.Context, id, requesterID string, in UpdatePagamentoInput) (*domain.PagamentoMensal, error)
}

// DeletePagamentoUseCase removes a payment.
type DeletePagamentoUseCase interface {
	Execute(ctx context.Context, id, requesterID string) error
}

// ConfirmarPagamentoUseCase marks a payment as paid.
type ConfirmarPagamentoUseCase interface {
	Execute(ctx context.Context, id, requesterID string, in ConfirmarPagamentoInput) (*domain.PagamentoMensal, error)
}

// UpsertConfigPagamentoUseCase creates or updates payment config for an event.
type UpsertConfigPagamentoUseCase interface {
	Execute(ctx context.Context, in UpsertConfigPagamentoInput) (*domain.EventoConfigPagamento, error)
}

// GetConfigPagamentoUseCase retrieves payment config for an event.
type GetConfigPagamentoUseCase interface {
	Execute(ctx context.Context, eventoID, requesterID string) (*domain.EventoConfigPagamento, error)
}

// ReaplicarFeePolicyNasConfigsUseCase reapplies the current fee policy snapshot
// to ALL existing EventoConfigPagamento documents. Admin/Moderator-only operation.
// Mirrors Java ReaplicarFeePolicySnapshotUseCase.
type ReaplicarFeePolicyNasConfigsUseCase interface {
	Execute(ctx context.Context, in ReaplicarFeePolicyNasConfigsInput) (*ReaplicarFeePolicyResult, error)
}
