package workflow_test

// TestWorkflowIdParity ensures that all workflow IDs generated by the Go
// implementation are byte-for-byte identical to the Java TemporalWorkflowIds
// counterparts.
//
// ⚠️  CRITICAL: If this test fails, signal-by-workflowId in production will be
// broken because the Go starters/signalers will address different IDs than the
// Java workers expect (and vice-versa during the Strangler Fig transition).

import (
	"testing"

	"github.com/stretchr/testify/assert"

	. "github.com/role-organizado/backend-go-role-organizado/internal/adapter/temporal/workflow"
)

func TestWorkflowIdParity(t *testing.T) {
	t.Parallel()

	// ── Per-execution primary IDs ─────────────────────────────────────────────
	// Each assertion mirrors the corresponding Java method in TemporalWorkflowIds.

	assert.Equal(t, "event-publication-real-draft-42", EventPublicationPrimaryID("draft-42"),
		"EventPublicationPrimaryID must match Java eventPublicationPrimary")

	assert.Equal(t, "outbound-real-req-99", OutboundPrimaryID("req-99"),
		"OutboundPrimaryID must match Java outboundPrimary")

	assert.Equal(t, "participant-lifecycle-real-evt1-part2", ParticipantLifecyclePrimaryID("evt1", "part2"),
		"ParticipantLifecyclePrimaryID must match Java participantLifecyclePrimary")

	assert.Equal(t, "psp-reconciliation-real-scope1-2026-01-01", PspReconciliationPrimaryID("scope1", "2026-01-01"),
		"PspReconciliationPrimaryID must match Java pspReconciliationPrimary")

	assert.Equal(t, "payment-expiration-real-tx-abc", PaymentExpirationPrimaryID("tx-abc"),
		"PaymentExpirationPrimaryID must match Java paymentExpirationPrimary")

	assert.Equal(t, "finance-reconciliation-real-2026-01-01", FinanceReconciliationPrimaryID("2026-01-01"),
		"FinanceReconciliationPrimaryID must match Java financeReconciliationPrimary")

	assert.Equal(t, "overdue-installment-real-2026-01-01", OverdueInstallmentPrimaryID("2026-01-01"),
		"OverdueInstallmentPrimaryID must match Java overdueInstallmentPrimary")

	assert.Equal(t, "invite-lifecycle-real-approval-xyz", InviteLifecyclePrimaryID("approval-xyz"),
		"InviteLifecyclePrimaryID must match Java inviteLifecyclePrimary")

	assert.Equal(t, "notification-fallback-real-notif-1", NotificationFallbackPrimaryID("notif-1"),
		"NotificationFallbackPrimaryID must match Java notificationFallbackPrimary")

	assert.Equal(t, "pricing-psp-review-real-2026-01-01", PricingPspReviewPrimaryID("2026-01-01"),
		"PricingPspReviewPrimaryID must match Java pricingPspReviewPrimary")

	assert.Equal(t, "event-publication-monitoring-real", EventPublicationMonitoringPrimaryID(),
		"EventPublicationMonitoringPrimaryID must match Java eventPublicationMonitoringPrimary (singleton)")

	assert.Equal(t, "participant-recalculation-real-evt-42", ParticipantRecalculationPrimaryID("evt-42"),
		"ParticipantRecalculationPrimaryID must match Java participantRecalculationPrimary")

	assert.Equal(t, "event-lifecycle-real-abc123", EventLifecyclePrimaryID("abc123"),
		"EventLifecyclePrimaryID must match Java eventLifecyclePrimary")

	// ── PaymentConfirmation: callbackType normalization ───────────────────────

	assert.Equal(t, "payment-confirmation-real-tx1-approved", PaymentConfirmationPrimaryID("tx1", "APPROVED"),
		"PaymentConfirmationPrimaryID must lower-case callbackType")

	assert.Equal(t, "payment-confirmation-real-tx1-failed", PaymentConfirmationPrimaryID("tx1", "FAILED"),
		"PaymentConfirmationPrimaryID must lower-case FAILED")

	assert.Equal(t, "payment-confirmation-real-tx1-cancelled", PaymentConfirmationPrimaryID("tx1", "CANCELLED"),
		"PaymentConfirmationPrimaryID must lower-case CANCELLED")

	assert.Equal(t, "payment-confirmation-real-tx1-unknown", PaymentConfirmationPrimaryID("tx1", ""),
		"PaymentConfirmationPrimaryID must map empty callbackType to 'unknown'")

	// ── AccountingSnapshot: key derivation ───────────────────────────────────

	assert.Equal(t, "accounting-snapshot-real-corr-123",
		AccountingSnapshotPrimaryID("2026-01-01", "2026-01-31", "corr-123"),
		"AccountingSnapshotPrimaryID must prefer correlationId")

	assert.Equal(t, "accounting-snapshot-real-2026-01-01_2026-01-31",
		AccountingSnapshotPrimaryID("2026-01-01", "2026-01-31", ""),
		"AccountingSnapshotPrimaryID must use dataInicio_dataFim when no correlationId")

	assert.Equal(t, "accounting-snapshot-real-all_today",
		AccountingSnapshotPrimaryID("", "", ""),
		"AccountingSnapshotPrimaryID must default to 'all_today' when all params empty")

	assert.Equal(t, "accounting-snapshot-real-2026-01-01_today",
		AccountingSnapshotPrimaryID("2026-01-01", "", ""),
		"AccountingSnapshotPrimaryID must default dataFim to 'today'")

	// ── Schedule constants: must be identical to Java ─────────────────────────

	assert.Equal(t, "psp-reconciliation-daily-workflow", PspReconciliationScheduledID,
		"PspReconciliationScheduledID must match Java PSP_RECONCILIATION_SCHEDULED")

	assert.Equal(t, "finance-reconciliation-daily-workflow", FinanceReconciliationScheduledID,
		"FinanceReconciliationScheduledID must match Java FINANCE_RECONCILIATION_SCHEDULED")

	assert.Equal(t, "overdue-installment-daily-workflow", OverdueInstallmentScheduledID,
		"OverdueInstallmentScheduledID must match Java OVERDUE_INSTALLMENT_SCHEDULED")

	assert.Equal(t, "pricing-psp-review-daily-workflow", PricingPspReviewScheduledID,
		"PricingPspReviewScheduledID must match Java PRICING_PSP_REVIEW_SCHEDULED")
}
